sudo: required
language: node_js
addons:
  chrome: stable
cache:
  yarn: true
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - stable
script:
  - yarn tsc -d
  - yarn lint
  - yarn test
  - yarn build
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
